name: AutoPull Caligo Server

on: [ push ]

jobs:
  update-server:
    runs-on: ubuntu-latest 
    steps:
      - name: Restart server
        run: |
          curl "https://lpanel.zanixon.xyz/api/client/servers/${{secrets.server_id}}/power" \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{secrets.apikey}}' \
            -X POST \
            -d '{
            "signal": "restart"
            }' 